# This is an example GitHub Actions workflow that will allow you to build your project with every push or pull request.
# For more information, see:
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: Rust Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    push:
      branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose